export const GET_TABLE_REQUEST = "GET_TABLE_REQUEST";
export const GET_TABLE_SUCCESS = "GET_TABLE_SUCCESS";
export const GET_TABLE_FAIL = "GET_TABLE_FAIL";

export const DELETE_ONE_ROW = "DELETE_ONE_ROW";
export const ACTIVE = "ACTIVE";
export const DESCRIPTION = "DESCRIPTION";
